### ISSUE TITLE
openapitools.json + generate error: requires option '-i'

### ISSUE THREAD

**Issue by streetclaw** [OpenAPITools/openapi-generator-cli#43]
Running `openapi-generator-cli generate` without additional parameter is not working: `[error] Required option '-i' is missing`

openapitools.json:
```json
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.0.0-beta2",
    "project-ts": {
        "generatorName": "typescript-axios",
        "output": "#{cwd}/src/api/#{name}",
        "glob": ".apiSchema/swagger/*.json"
    }
  }
}
```

package.json (excerpt):
```json
"scripts": {
"generate:openapi": "openapi-generator-cli generate"
}
```

- command: `npm run generate:openapi` in project root
- valid openapi json in `.apiSchema/swagger`
- CLI version: `2.0.2`
- Locally installed

**Comment by kay-schecker** [comment]
I guess it's an issue with the current cwd. I'll fix it asap

**Comment by kay-schecker** [comment]
which OS, Node and NPM you are using?

**Comment by streetclaw** [comment]
- npm: `6.14.8`
- os: `macOS 10.15.7`

**Comment by kay-schecker** [comment]
fixed with v2.0.3

**Comment by streetclaw** [comment]
The error still appears with version 2.0.3. At least for me. Minimal example (tested on macOS, arch linux and windows):
[cli_example.zip](https://github.com/OpenAPITools/openapi-generator-cli/files/5357090/cli_example.zip)

1. run `npm install` to install openapi-generator-cli version 2.0.3
2. run `npm generate:openapi`

**Comment by kay-schecker** [comment]
Thanks, I'll check

**Comment by kay-schecker** [comment]
You missed the generators node:

`{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.0.0-beta2",
    "generators": {
      "project-ts": {
        "generatorName": "typescript-axios",
        "output": "#{cwd}/src/api/#{name}",
        "glob": ".apiSchema/swagger/*.json"
      }
    }
  }
}`

**Comment by kay-schecker** [comment]
I'll add a new feature to validate the given config ...

**Comment by streetclaw** [comment]
Yes, sorry I should have noticed.

**Comment by RichardBradley** [comment]
I still get this error on the latest version.

Is there a workaround? I can't even figure out how to get this tool to print what Java command it is invoking so I can work around.

I'm on v 2.5.2 (latest at time of writing), Cygwin on Windows, Node 14. Here's all relevant info I can think of:

```
$ npx --version
6.14.17
$ npm --version
6.14.17
$ node --version
v14.20.0
$ npx openapi-generator-cli version
6.0.1
$ grep openapi-generator ../../package.json
    "@openapitools/openapi-generator-cli": "^2.5.2",
$ cat openapitools.json
{
  "$schema": "../../node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "6.0.0",
    "generators": {
      "my-spec-gen": {
        "generatorName": "typescript-rxjs",
        "output": "./generated",
        "inputSpec": "./reference/my-spec.yaml"
      }
    }
  }
}
$ npx openapi-generator-cli generate
Download 6.0.1 ...
Downloaded 6.0.1
[error] Required option '-i' is missing
```

Any ideas what I can do to diagnose or fix?

**Comment by RichardBradley** [comment]
I was able to work around by invoking Java directly:

```
 java -jar ../../node_modules/@openapitools/openapi-generator-cli/versions/6.0.1.jar generate -i ./reference/my-api.yaml -o generated -g typescript-rxjs
```

.. still not sure what's up with `openapi-generator-cli` or how to diagnose further. I wasn't able to get any diagnostic logs, and the main.js seems minified so I couldn't investigate further.

**Comment by momesana** [comment]
We have the same issue with `pnpm`. It happens when we invoke pnpm with --dir from outside the project's root folder i.e.:
```bash
pnpm --dir <path to the projects root folder> run generate-sources
```
`generate-sources` in turn is defined as follows in the respective `package.json`'s script section:
```json
generate-sources": "openapi-generator-cli generate"
```
The generation of types runs as part of the CI on windows, mac and linux. It only fails on windows. Furthermore it didn't cause any problems when used with `yarn` and only appeared after switching to pnpm. The workaround for us is to change into the project directory and execute pnpm without --dir. It's worth noting that we have a bunch of different scripts all executed with `--dir` and they work flawlessly across all systems so this is likely an issue that pertains to `openapi-generator-cli` and not to `pnpm` etc..

**Comment by tajnymag** [comment]
Found the issue!

Openapi-generator-cli is using INIT_CWD as its working directory:
https://github.com/OpenAPITools/openapi-generator-cli/blob/7e43a4e4f91148dede80fb7849eb473db759eb17/apps/generator-cli/src/app/services/config.service.ts#L10

When I ran my pnpm test script from a different directory (`pnpm -r` or `pnpm run --dir`) I got:
```
> node cwd-test.js

process.env.PWD undefined
process.env.INIT_CWD C:\Users\marek\GitHub\vsb-eink-services
process.cwd() C:\Users\marek\GitHub\vsb-eink-services\packages\facade-api-client
```

There's an [issue](https://github.com/pnpm/pnpm/issues/7042) in pnpm discussing where INIT_CWD is supposed to point.
